### ISSUE TITLE
[Idea] west module

### ISSUE THREAD

**Issue by elpekenin** [joelspadin/zmk-locale-generator#8]
Opening this just so that the idea isn't lost. Feel free to close if you dont like it or want to implement.

As raised on discord, i think it would be nice to have a west module (aka GitHub repo with a `zephyr/module.yaml`) to expose this useful headers in a way that is easier to use (and would also get updated automatically when building with GHA).

As such, the files should be part of a repo (this? another one?) instead of being published as a release (or perhaps have both ways of getting them).

**Comment by joelspadin** [comment]
A module is now available: https://github.com/joelspadin/zmk-locales
